return {
  { "ellisonleao/gruvbox.nvim" },
  { "sainnhe/gruvbox-material" },
  { "mhartington/oceanic-next" },
  { "sainnhe/sonokai" },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "sonokai",
      icons = {
        dap = {
          Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
          Breakpoint = " ",
          BreakpointCondition = " ",
          BreakpointRejected = { " ", "DiagnosticError" },
          LogPoint = "> ",
        },
        diagnostics = {
          Error = " ",
          Warn = " ",
          Hint = " ",
          Info = " ",
        },
        git = {
          added = "~",
          modified = "~",
          removed = "~",
        },
        kinds = {
          Array = "~",
          Boolean = "~",
          Copilot = "~",
          Key = "~",
          Namespace = "{}~",
          Null = "∅~",
          Number = "№~",
          Object = "~",
          Package = "~",
          String = "󰅳~",
          Text = "󰦨~",
          Method = "m~",
          Function = "󰊕~", -- 
          Constructor = "~",
          Field = "~",
          Variable = "󰫧~",
          Class = "~",
          Interface = "~",
          Module = "~",
          Property = "~",
          Unit = "~",
          Value = "v~",
          Enum = "~",
          Keyword = "~",
          Snippet = "~",
          Color = "~",
          File = "~",
          Reference = "~",
          Folder = "~",
          EnumMember = "~",
          Constant = "~",
          Struct = "~",
          Event = "~",
          TypeParameter = "~",
          Operator = "~",
        },
      },
    },
  },
}

-- for Monolisa font
-- kinds = {
--           Array = "~",
--           Boolean = "~",
--           Copilot = "~",
--           Key = "~",
--           Namespace = "~",
--           Null = "∅~",
--           Number = "№~",
--           Object = "~",
--           Package = "~",
--           String = "~",
--           Text = "~",
--           Method = "m~",
--           Function = "󰊕~", -- 
--           Constructor = "~",
--           Field = "~",
--           Variable = "~",
--           Class = "~",
--           Interface = "~",
--           Module = "~",
--           Property = "~",
--           Unit = "~",
--           Value = "~",
--           Enum = "~",
--           Keyword = "~",
--           Snippet = "~",
--           Color = "~",
--           File = "~",
--           Reference = "~",
--           Folder = "~",
--           EnumMember = "~",
--           Constant = "~",
--           Struct = "~",
--           Event = "~",
--           TypeParameter = "~",
--           Operator = "~",
--         },
