return {
  { "ellisonleao/gruvbox.nvim" },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox",
      icons = {
        dap = {
          Stopped = { "", "DiagnosticWarn", "DapStoppedLine" },
          Breakpoint = " ",
          BreakpointCondition = " ",
          BreakpointRejected = { " ", "DiagnosticError" },
          LogPoint = ".>",
        },
        diagnostics = {
          Error = "",
          Warn = "",
          Hint = "",
          Info = "",
        },
        git = {
          added = "",
          modified = "",
          removed = "",
        },
        kinds = {
          Array = "",
          Boolean = "",
          Copilot = "",
          Key = "",
          Namespace = "",
          Null = "∅",
          Number = "№",
          Object = "",
          Package = "",
          String = "",
          Text = "",
          Method = "m",
          Function = "",
          Constructor = "",
          Field = "",
          Variable = "",
          Class = "",
          Interface = "",
          Module = "",
          Property = "",
          Unit = "",
          Value = "",
          Enum = "",
          Keyword = "",
          Snippet = "",
          Color = "",
          File = "",
          Reference = "",
          Folder = "",
          EnumMember = "",
          Constant = "",
          Struct = "",
          Event = "",
          Operator = "",
          TypeParameter = "",
        },
      },
    },
  },
}
